name: 'WordPress Plugin Deploy'
description: 'Deploy to the WordPress Plugin Repository'
author: 'priyank'
inputs:
  generate-zip:
    description: 'Generate package zip file?'
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.generate-zip }}
branding:
  icon: 'upload-cloud'
  color: 'blue'
